version: "3.8"

services:
  db:
    image: mariadb:12.0
    container_name: test_mariadb
    ports:
      - "3306:3306"
    environment:
      MARIADB_ROOT_PASSWORD: password
      MARIADB_DATABASE: CommonsenseDB
    healthcheck:
      test: ["CMD", "mariadb-admin", "ping", "-ppassword"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - db_data_2:/var/lib/mysql

volumes:
  db_data_2:
