name: Run Tests (End-to-End)

on: [push]

jobs:
  cypress-test:
    name: Run Cypress tests
    env:
      MYSQL_USER: "root"
      MYSQL_PWD: "password"
      MYSQL_DB: "CommonsenseDB"
      MYSQL_HOST: "127.0.0.1"
      MYSQL_PORT: "33306"
      SESSION_SECRET: "secret"

    runs-on: ubuntu-latest

    services:
      db:
        image: mysql:8
        ports:
          - 33306:3306
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: CommonsenseDB
        options: >-
          --health-cmd "mysqladmin ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Create database
        run: |
          mysql --protocol=tcp -h ${{ env.MYSQL_HOST }} --port ${{ env.MYSQL_PORT }} -u${{ env.MYSQL_USER }} -p${{ env.MYSQL_PWD }} -e "CREATE DATABASE IF NOT EXISTS ${{ env.MYSQL_DB }};"

      - name: Seed the database
        run: |
          mysql --protocol=tcp -h ${{ env.MYSQL_HOST }} --port ${{ env.MYSQL_PORT }} -u${{ env.MYSQL_USER }} -p${{ env.MYSQL_PWD }} ${{ env.MYSQL_DB }} < test/init.sql

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18.x"

      - name: Install server dependencies
        working-directory: server
        run: npm install

      - name: Start backend server
        working-directory: server
        run: node server.js &
        env:
          DB_USER: ${{ env.MYSQL_USER }}
          DB_PASSWORD: ${{ env.MYSQL_PWD }}
          DB_NAME: ${{ env.MYSQL_DB }}
          DB_HOST: ${{ env.MYSQL_HOST }}
          DB_PORT: ${{ env.MYSQL_PORT }}
          DB_DRIVER: "mysql"
          SESSION_SECRET: ${{ env.SESSION_SECRET }}

      - name: Wait for backend server to be ready
        run: sleep 10

      - name: Install client dependencies
        working-directory: client
        run: |
          echo NODE_ENV=development > .env
          echo NODE_ENV
          CYPRESS_CACHE_FOLDER=/home/runner/.cache/Cypress npm install & npm run dev &

      - name: Run Cypress tests
        working-directory: client
        run: CYPRESS_CACHE_FOLDER=/home/runner/.cache/Cypress npx cypress run --record --key ${{ secrets.CYPRESS_RECORD_KEY }}
