import React, { useState, useRef, useEffect } from "react";
import FeaturesElement2 from "../images/Common-Sens.png";

const AboutPartial: React.FC = () => {
  const [tab, setTab] = useState<number>(1);

  const tabs = useRef<HTMLDivElement | null>(null);

  const heightFix = () => {
    if (tabs.current?.children[tab - 1]) {
      const childElement = tabs.current.children[tab - 1] as HTMLElement;
      tabs.current.style.height = childElement.offsetHeight + "px";
    }
  };

  useEffect(() => {
    heightFix();
  }, [tab]);

  return (
    <section id="about" className="relative">
      <div
        className="absolute inset-0 bg-gray-100 pointer-events-none"
        aria-hidden="true"
      ></div>

      <div className="relative max-w-6xl mx-auto px-4 sm:px-6">
        <div className="pt-12 md:pt-20">
          {/* Section header */}
          <div className="max-w-3xl mx-auto text-center pb-12 md:pb-16">
            <h1 className="h2 mb-4">How “Common” is Common Sense?</h1>
          </div>
          <div className="max-w-3xl mx-auto pb-12 md:pb-16 text-justify text-xl text-gray-600">
            <p className="mb-2">
              Common sense is usually defined as “what all sensible people
              know,” but this definition is circular: how do we know someone is
              sensible other than that they possess common sense? As a result,
              most people believe that they themselves possess common sense, but
              have trouble articulating which of their beliefs are commonsense
              or how common they are.
            </p>
            <p className="mb-2">
              This project seeks to resolve the intrinsic ambiguity of common
              sense empirically via a massive online survey experiment.
              Participants will rate short statements "claims" that span a wide
              range of knowledge domains, both in terms of their own claim with
              the statement and their belief about what others will say. We have
              developed novel methods to extract statements from several diverse
              sources including appearances in mass media, non-fiction books,
              and political campaign emails, as well as statements elicited from
              human respondents and generated by AI systems. We have also
              developed new taxonomies to classify statements by domain and
              type.
            </p>

            <p className="mb-2">
              Ultimately, we hope to provide insight into the nature and limits
              of common sense, thereby aiding research communities (e.g. AI and
              ML) who wish to explore and simulate this ubiquitous yet
              frustratingly elusive concept.
            </p>
            {/* 
            <p className="mb-2">
              Read about the research{" "}
              <a href="" className="underline">
                here
              </a>
              .
            </p> */}
          </div>
        </div>
      </div>
    </section>
  );
};

export default AboutPartial;
